### PR TITLE
Resolve bug 61

### PR DESCRIPTION
**Pull request by lpiron**

### CODE REVIEW

**Comment by sandersaares** [comment]
@heronyme are you available to review? Does it resolve the issues you raised?

**Comment by Heronyme** [comment]
Hello. Yes, thanks, this addresses the issues related to the spec and the XSD. Points 1, 2 and 4. Point 3, related to example CPIX-s, is not yet addressed.

Except, about the "unique" constraint:
When trying out the added uniqueness constraint it doesn't invalidate a document with duplicate "playlist" values for me. Does it work in your test code? I'm not an XSD specialist, but as it's added currently, doesn't it also define multiple root-level elements in the XML (CPIX and DRMSystem), which doesn't look valid to me:

```
	<xs:element name="CPIX" type="cpix:CpixType"/>
	<xs:element name="DRMSystem" type="cpix:DRMSystemType">
		<xs:unique name="uniquePlaylist">
			<xs:selector xpath="."/>
			<xs:field xpath="@playlist"/>
		</xs:unique>
	</xs:element>
```

I would have added the constraint where the "DRMSystem" element was originally specified:
```
	<xs:complexType name="DRMSystemListType">
		<xs:sequence>
			<xs:element name="DRMSystem" type="cpix:DRMSystemType" minOccurs="0" maxOccurs="unbounded">
 				<xs:unique name="uniquePlaylistForHLSSignalingData">
					<xs:selector xpath="cpix:HLSSignalingData"/>
					<xs:field xpath="@playlist"/>
				</xs:unique>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="optional"/>
		<xs:attribute name="updateVersion" type="xs:integer" use="optional"/>
	</xs:complexType>
```

**Comment by lpiron** [comment]
You have it right for the XSD, I corrected accordingly. Please check, it seems to work but I'm not an expert in XSD.
For the examples, there is an action item for Sander for checking if some new examples canbe genrated based on different DRM data, if yes, then all bugs on examples would be solved, if not, thenwe will check them one by one.

**Comment by Heronyme** [comment]
Looks good!

**Pull request merged**
