### PR TITLE
Converted diagrams to PlantUML files

### PR DESCRIPTION
**Pull request by sandersaares**
I converted a bunch of the diagrams (the ones I understood) to PlantUML text files, from which PNGs are automatically generated at publishing time. This makes it easier to edit the files using text, without having to rely on graphical tools.

I am not 100% satisfied with the layout of the DocumentKeyStructure diagram but I guess that is the price of automation - the computer gets to do the fine tuning and not you.

A fair bit of diagrams remain in PNG form. Mostly because I did not understand what they were supposed to represent so I could not be sure how to best convert them.

I attach build output for easy review purposes since we do not yet have the automated builds set up:
[Html.zip](https://github.com/Dash-Industry-Forum/CPIX/files/1806686/Html.zip)
[Index.pdf](https://github.com/Dash-Industry-Forum/CPIX/files/1806687/Index.pdf)

### CODE REVIEW

**Comment by lpiron** [comment]
Not the same layout than the ones in Words but this is fine.
Did you try having figure 8 in one part ? That was too small ?

**Comment by sandersaares** [comment]
PlantUML sequence diagrams seem to be strictly horizontal, so it got very stretched out. This seemed to be the optimal compromise solution for figure 8 that I was able to come up with. Maybe some more experimentation can bring out an even better solution, though?

**Comment by lpiron** [comment]
OK, fine. I guess we will have to spend time and experiment on this tool also.

**Comment by sandersaares** [comment]
Discussed over email and merging.

**Pull request merged**
